[package]
name = "demo"
version = "0.1.0"
authors = ["gonzo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emballoc = "0.3.0"
libc = "0.2"

[profile.release]
lto=true
opt-level=2
#debug=true
